In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [40]:
# carregando o conjunto de dados para um Pandas DataFrame
credit_card_data = pd.read_csv("/creditcard.csv")
# primeiras 5 linhas do conjunto de dados
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [42]:
# informaÃ§Ãµes do conjunto de dados
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25838 entries, 0 to 25837
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    25838 non-null  int64
 1   V1      25838 non-null  float64
 2   V2      25838 non-null  float64
 3   V3      25837 non-null  float64
 4   V4      25837 non-null  float64
 5   V5      25837 non-null  float64
 6   V6      25837 non-null  float64
 7   V7      25837 non-null  float64
 8   V8      25837 non-null  float64
 9   V9      25837 non-null  float64
 10  V10     25837 non-null  float64
 11  V11     25837 non-null  float64
 12  V12     25837 non-null  float64
 13  V13     25837 non-null  float64
 14  V14     25837 non-null  float64
 15  V15     25837 non-null  float64
 16  V16     25837 non-null  float64
 17  V17     25837 non-null  float64
 18  V18     25837 non-null  float64
 19  V19     25837 non-null  float64
 20  V20     25837 non-null  float64
 21  V21     25837 non-null  float64
 22  V22     25837 non-null  float64
 23  V23     25837 non-null  float64
 24  V24     25837 non-null  float64
 25  V25     25837 non-null  float64
 26  V26     25837 non-null  float64
 27  V27     25837 non-null  float64
 28  V28     25837 non-null  float64
 29  Amount  25837 non-null  float64
 30  Class   25837 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.1 MB

In [43]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [44]:
result = credit_card_data

In [46]:
result = result.dropna()

In [47]:
result.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [49]:
result['Class'].value_counts()

Class
0.0    25749
1.0       88
Name: count, dtype: int64

This Dataset is highly unbalanced

0 â†’ Normal Transaction

1 â†’ Fraudulent transaction

In [50]:
# separando os dados para anÃ¡lise
legit = result[result.Class == 0 ]
fraud = result[result.Class == 1 ]

In [51]:
legit.Amount.describe()

count    25749.000000
mean        75.726227
std        219.488324
min          0.000000
25%          6.200000
50%         18.960000
75%         67.500000
max       7879.420000
Name: Amount, dtype: float64

In [56]:
fraud.Amount.describe()

count      88.000000
mean      100.010000
std       265.845031
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [57]:
result.groupby( 'Class' ).mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,19380.491087,-0.197045,0.145743,0.767372,0.208854,-0.174420,0.088572,-0.100712,0.011278,0.453641,...,0.039986,-0.039570,-0.131409,-0.038716,0.012076,0.128670,0.022883,0.010424,0.003824,75.726227
1.0,17935.875000,-8.613716,6.376169,-12.221731,6.231847,-6.027247,-2.487080,-8.308784,4.351326,-2.987199,...,0.714069,0.539387,-0.381823,-0.350615,-0.252970,0.346695,0.179760,0.856336,0.100578,100.010000

In [58]:
legit_sample = legit.sample(n=88)

In [59]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [60]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
9123,12881,-0.377447,1.172630,1.400290,0.218569,0.248492,-0.473566,0.516769,0.007570,0.947665,...,-0.391917,-0.794127,0.029738,-0.049354,-0.270758,0.064346,0.233008,0.087465,2.97,0.0
8420,11286,-0.704500,-3.343868,0.066035,1.528503,-1.911144,0.461467,0.344277,-0.028690,2.025925,...,0.543710,-0.361674,-0.934212,0.014315,-0.096460,0.438684,-0.221483,0.170029,984.00,0.0
10499,17234,1.357134,0.386000,-0.150747,0.574108,0.331967,-0.238955,-0.075889,-0.161044,1.503232,...,-0.536863,-1.322689,-0.024994,-1.134272,0.359672,0.144603,-0.055557,0.008971,1.98,0.0
19901,30635,-0.996779,0.381929,2.689263,0.420386,-1.073033,0.508003,-0.390623,0.574800,1.247924,...,-0.147786,0.111542,-0.119358,0.559311,-0.130725,0.336325,0.482262,0.248561,19.45,0.0
20516,31094,1.264503,0.596742,-0.405407,1.235933,0.125923,-1.012707,0.230977,-0.172489,0.073469,...,-0.085503,-0.215374,-0.153307,-0.106925,0.710231,-0.302391,0.025795,0.045760,1.00,0.0

In [61]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,19083.193182,-0.113597,0.221665,0.718192,0.197477,-0.361042,0.140481,-0.117067,0.169568,0.712884,...,0.084963,-0.095496,-0.106719,-0.036549,0.103012,0.092504,0.003397,-0.025889,-0.050756,70.782273
1.0,17935.875000,-8.613716,6.376169,-12.221731,6.231847,-6.027247,-2.487080,-8.308784,4.351326,-2.987199,...,0.714069,0.539387,-0.381823,-0.350615,-0.252970,0.346695,0.179760,0.856336,0.100578,100.010000

In [62]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [64]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(176, 30) (140, 30) (36, 30)

Treinamento de modelo

empregamos RegressÃ£o LogÃ­stica, inicializando o modelo com parÃ¢metros padrÃ£o. Usando os dados de treinamento (X_train e Y_train), ajustamos o modelo de RegressÃ£o LogÃ­stica para aprender padrÃµes nos dados. Esse processo envolve o ajuste de parÃ¢metros do modelo para minimizar a diferenÃ§a entre rÃ³tulos de classe reais e previstos.

In [65]:
model = LogisticRegression()
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [66]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9857142857142858

A pontuaÃ§Ã£o de precisÃ£o nos dados de treinamento Ã© de aproximadamente 98%. Isso indica que o modelo de RegressÃ£o LogÃ­stica prevÃª corretamente os rÃ³tulos de classe para cerca de 98% das instÃ¢ncias no conjunto de dados de treinamento.

In [67]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.8888888888888888

author : https://medium.com/@saibhargavkarnati/credit-card-fraud-detection-using-ml-22b38a78168e